Added information for implementators
daisy/transitiontoepub pull request #31
Opened 2024-04-16 03:16 UTC by GeorgeKerscher

I took a stab at addinformation for NVDA or Jaws folks. It needs comments and discussion. It is only partially completed.

2024-04-16 07:56 UTC, gregoriopellegrino commented
Hi George,
to understand how you constructed these comments: did you start from the shared Excel file where we had identified priorities?

2024-04-16 13:17 UTC, GeorgeKerscher commented
Yes, I used the values from the spreadsheet in this repo.

2024-04-16 13:51 UTC, clapierre approved these changes
Looks good George.  
I noticed at least in the preview from GitHub every time you had word"xxxx" there is no space between word and your first quotation mark.

2024-04-16 15:27 UTC, gautierchomel requested changes

2024-04-16 15:27 UTC, gautierchomel commented on dpub-aria-testing/content/DPUB-ARIA-tests.xhtml
> +<p>Suggested output "dedication."
Closing P missing here.

2024-04-16 15:27 UTC, gautierchomel commented
[Preview](https://rawcdn.githack.com/daisy/transitiontoepub/957e2d55341567ff6522f94cb4d2b93b311a79c8/dpub-aria-testing/content/DPUB-ARIA-tests.xhtml)

2024-04-16 23:19 UTC, GeorgeKerscher commented
I put all the information from the Google Sheets repo. I also added guidance for implementors. I think it is fairly good. The actionable items may need some work.

2024-04-17 13:36 UTC, clapierre commented on dpub-aria-testing/content/DPUB-ARIA-tests.xhtml
> +    <p>This is a critical  priority. Many times, the word"footnote" would be included in the heading associated with this item. It should  always ve vocalized.</p>
word"footnote" missing space before initial quotation mark.

2024-04-18 17:37 UTC, merged